[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', '../../node_modules', 'artifacts']
test = 'test/foundry'
cache_path  = 'forge-cache'

[profile.default.fuzz]
max_test_rejects = 100000000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
