[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib', '../../node_modules', 'artifacts']
test = 'test'
cache_path  = 'forge-cache'
gas_reports = ["*"]

[profile.default.fuzz]
max_test_rejects = 100000000